<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true' "/>

  <PropertyGroup>
    <Title>Lombiq Hosting - Media Theme Bridge for Orchard Core</Title>
    <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Media Theme Bridge for Orchard Core: Provides the processing logic for the Media Theme. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Media;Module</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Media-Theme</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Media-Theme</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Deployment.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.DisplayManagement.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Recipes.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.ResourceManagement.Abstractions" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="OrchardCore.Media" Version="$(OrchardCoreVersion)" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
    <ProjectReference Include="..\..\..\Modules\Lombiq.HelpfulExtensions\Lombiq.HelpfulExtensions\Lombiq.HelpfulExtensions.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.5.0" />
    <PackageReference Include="Lombiq.HelpfulExtensions" Version="11.1.0" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true' "/>

</Project>
