<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OrchardCoreProjectType>Theme</OrchardCoreProjectType>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Title>Lombiq Hosting - Media Theme Tests Theme for Orchard Core</Title>
    <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Media Theme Tests Theme for Orchard Core: With the help of this test theme, you'll can tests basic media theme logic.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Media;Theme</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Media-Theme</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Media-Theme</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.ContentManagement" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.Hosting.MediaTheme.Bridge\Lombiq.Hosting.MediaTheme.Bridge.csproj" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Module.Targets/Lombiq.MSBuild.Module.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'" />

</Project>
