<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Tests.UI.Targets/Lombiq.MSBuild.Tests.UI.Targets.props" />

    <PropertyGroup>
        <Title>Lombiq Hosting - Media Theme for Orchard Core - UI Test Extensions</Title>
        <Authors>Lombiq Technologies</Authors>
        <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
        <Description>Lombiq Hosting - Media Theme for Orchard Core - UI Test Extensions: Extensions to aid in UI testing Lombiq Hosting - Media Theme for Orchard Core. See the project website for detailed documentation.</Description>
        <PackageIcon>NuGetIcon.png</PackageIcon>
        <PackageTags>OrchardCore;Lombiq;AspNetCore;Media;Theme</PackageTags>
        <RepositoryUrl>https://github.com/Lombiq/Hosting-Media-Theme</RepositoryUrl>
        <PackageProjectUrl>https://github.com/Lombiq/Hosting-Media-Theme/blob/dev/Readme.md</PackageProjectUrl>
        <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    </PropertyGroup>

</Project>
