<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.Tests.UI.Targets/Lombiq.MSBuild.Tests.UI.Targets.props"/>

  <PropertyGroup>
    <Title>Lombiq Hosting - Media Theme for Orchard Core - UI Bridge Test Extensions</Title>
    <Copyright>Copyright © 2022, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Hosting - Media Theme for Orchard Core - UI Bridge Test Extensions: Extensions to aid in UI bridge testing Lombiq Hosting - Media Theme for Orchard Core. See the project website for detailed documentation.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Media;Theme</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Hosting-Media-Theme</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Hosting-Media-Theme/blob/dev/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lombiq.Hosting.MediaTheme.Bridge\Lombiq.Hosting.MediaTheme.Bridge.csproj"/>
    <ProjectReference Include="..\Lombiq.Hosting.MediaTheme.Tests.UI\Lombiq.Hosting.MediaTheme.Tests.UI.csproj"/>
  </ItemGroup>

</Project>
